#!/usr/bin/env python

# Usage:
#
#   dedupe.py [--delete=true|--dry-run=true] <config.json> 
#
# Without --delete or --dry_run, the tool only searches for duplicates.
# With --dry_run, the list of paths that would be deleted is printed.
# With --delete, paths are actually deleted! (Use with caution!)
# --dry_run and --delete cannot be true at the same time.
#
# config.json structure:
#
#   {
#       "sources": {
#           "source-id-1": "source-file-1.jsonl",
#           "source-id-2": "source-file-2.jsonl"
#       },
#       "digests_to_ignore": [
#           "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
#       ],
#       "dont_dedupe_prefix": [
#           "/some/dir/with/dupes/",
#       ],
#       "canonical_roots": {
#           "/path/canonical-1/": {
#               "/path/duplicate-1": "DELETE"
#           },
#           "/path/canonical-2/": {
#               "/mnt/storage/Music.bak/": "DELETE"
#           }
#       }
#   }
#
# The source files are generated by index.py.
#
# For canonical root, the structure is:
# canonical_prefix -> dupe_prefix -> action.
#
# action must be DELETE. The meaning is that if for a certain digest, the set of
# duplicates contains a match with canonical_prefix, then all files that match
# dupe_prefix will be deleted.
#
# Note all directory prefixes should be /-terminated or they may match siblings
# unintentionally; e.g. prefix "/foo" would match "/foo/bar" and "/foobar", but
# the latter is probably unintentional, so use prefix "/foo/" instead.
#
# It is important that canonical and dupe roots are disjoint!
#
# A structure like {"/foo": {"/foo/bar": DELETE}} would cause "/foo/bar/baz" to
# be considered a duplicate of itself and be deleted incorrectly.

from collections import defaultdict
import argparse
import codecs
import hashlib
import json
import os
import sys

digest_to_paths = defaultdict(list)  # digest -> list of paths
path_to_digest = {}
path_to_source = {}

digests_to_ignore = None
dont_dedupe_prefix = None
canonical_roots = None  # canonical path prefix -> dupe path prefix -> action ("DELETE")

counts = {
    "unique": 0,
    "dupe_children": 0,
    "ignored_digest": 0,
    "ignored_prefix": 0,
    "delete": 0,
    "unresolved": 0
}

DIGEST_SIZE = hashlib.sha256().digest_size

def ParseDigest(hexdigest):
    assert isinstance(hexdigest, str)
    digest = bytes.fromhex(hexdigest)
    assert len(digest) == DIGEST_SIZE
    return digest


def DecideDupesToDelete(digest, dupes):
    '''Returns None if it should not be considered a dupe, or a set of dupes to delete (which may be empty).'''
    assert len(dupes) >= 1

    if len(dupes) == 1:
        counts['unique'] += 1
        return None

    if digest in digests_to_ignore:
        counts['ignored_digest'] += 1
        return None

    # Consider speeding this up with a trie or sorted set or something?
    for prefix in dont_dedupe_prefix:
        if all(dupe.startswith(prefix) for dupe in dupes):
            counts['ignored_prefix'] += 1
            return None

    to_delete = set()
    for canonical_prefix in canonical_roots:
        if any(dupe.startswith(canonical_prefix) for dupe in dupes):
            for dupe_prefix, action in canonical_roots[canonical_prefix].items():
                assert action == 'DELETE'
                for dupe in dupes:
                    if dupe.startswith(dupe_prefix):
                        to_delete.add(dupe)

    if len(to_delete) == 0:
        counts['unresolved'] += 1
    else:
        counts['delete'] += 1

    return to_delete

def ReadIndexFile(source, index_file):
    with open(index_file, 'rt') as f:
        for line in f:
            obj = json.loads(line)
            path = obj['path']
            assert isinstance(path, str)
            hexdigest = obj['sha256']
            digest = ParseDigest(hexdigest)
            assert path not in path_to_digest
            path_to_digest[path] = digest
            digest_to_paths[digest].append(path)
            path_to_source[path] = source

def Main(config_filename, *, dry_run=False, delete=False):
    global digests_to_ignore, dont_dedupe_prefix, canonical_roots

    with open(config_filename, 'rt') as f:
        config = json.load(f)

    digests_to_ignore = set(ParseDigest(hexdigest) for hexdigest in config['digests_to_ignore'])
    dont_dedupe_prefix = set(config['dont_dedupe_prefix'])
    canonical_roots = config['canonical_roots']

    for source, index_file in config['sources'].items():
        ReadIndexFile(source, index_file)

    sorted_paths = sorted(path_to_digest)
    to_delete = set()

    digest_is_dupe = {}
    last_dupe_dir = None
    for path in sorted_paths:
        if last_dupe_dir is not None and path.startswith(last_dupe_dir):
            counts['dupe_children'] += 1
            continue  # ancestor already marked as dupe

        digest = path_to_digest[path]

        is_dupe = digest_is_dupe.get(digest)
        if is_dupe is not None:
            is_new = False
            dupes = None
            dupes_to_delete = None
        else:
            is_new = True
            dupes = digest_to_paths[digest]
            dupes_to_delete = DecideDupesToDelete(digest, dupes)
            is_dupe = dupes_to_delete is not None
            digest_is_dupe[digest] = is_dupe

        if not is_dupe:
            continue

        if path.endswith('/'):
            last_dupe_dir = path

        if not is_new:
            continue
            
        assert path in dupes

        dupes_to_delete = set(dupes_to_delete)
        assert dupes_to_delete != set(dupes)

        to_delete.update(dupes_to_delete)

        # Report dupes
        print(digest.hex(), file=sys.stderr)
        for dupe in dupes:
            print('\t', [" (keep)", "DELETE"][dupe in dupes_to_delete], dupe, file=sys.stderr)
        print(file=sys.stderr)

    print('Digest resolution counts:', file=sys.stderr)
    for key, value in sorted(counts.items()):
        print('%20s: %10d'%(key, value), file=sys.stderr)

    if not (dry_run or delete):
        return

    # At this point, to_delete contains only top-level files and directories to delete.
    # Augment it with the descendants of directories so we can recursively delete
    # without overdeleting (e.g. if a file has been added to a directory since we
    # computed the # index we do not want to delete it!)
    to_delete_list = []
    last_deleted_dir = None
    for path in sorted_paths:
        if last_deleted_dir is not None and path.startswith(last_deleted_dir):
            to_delete_list.append(path)
            continue
        if path in to_delete:
            to_delete_list.append(path)
            if path.endswith('/'):
                last_deleted_dir = path

    # Now actually delete!
    for path in reversed(to_delete_list):
        if delete:
            print('Deleting', path)
            try:
                if path.endswith('/'):
                    os.rmdir(path)
                else:
                    os.remove(path)
            except FileNotFoundError:
                pass
        else:
            print('Would delete', path)


parser = argparse.ArgumentParser(description='Deduplicate')
parser.add_argument('--dry-run', type=bool, default=False)
parser.add_argument('--delete', type=bool, default=False)
parser.add_argument('config_json', type=str, default=None)
args = parser.parse_args()
assert not (args.dry_run and args.delete)
Main(config_filename=args.config_json, dry_run=args.dry_run, delete=args.delete)
